#!/usr/bin/env python3
"""
Google Gemini API integration for AI article generation
"""

import os
import re
from typing import Dict, Any
import google.generativeai as genai
from google.generativeai.types import HarmCategory, HarmBlockThreshold

class GeminiArticleGenerator:
    def __init__(self, api_key: str = None):
        """Initialize Gemini API client"""
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required")
        
        # Configure the API
        genai.configure(api_key=self.api_key)
        
        # Use Gemini 1.5 Flash for faster, cost-effective generation
        self.model = genai.GenerativeModel(
            model_name="gemini-1.5-flash",
            safety_settings={
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE,
            },
            generation_config=genai.types.GenerationConfig(
                temperature=0.7,
                top_p=0.9,
                max_output_tokens=2000,
            )
        )
    
    def generate_article(self, 
                        product_info: Dict[str, Any],
                        article_type: str,
                        tone: str,
                        keywords: str,
                        length: str,
                        include_comparison: str,
                        target_audience: str,
                        seo_focus: str) -> str:
        """
        Generate an article using Google Gemini API
        """
        
        # Build the prompt based on parameters
        prompt = self._build_prompt(
            product_info, article_type, tone, keywords, length,
            include_comparison, target_audience, seo_focus
        )
        
        try:
            # Generate content using Gemini
            response = self.model.generate_content(prompt)
            
            if response.text:
                article_content = response.text
                
                # Clean up the response
                article_content = self._clean_response(article_content)
                
                # Don't add affiliate elements here - the content pipeline template handles that
                return article_content
            else:
                raise Exception("No content generated by Gemini API")
                
        except Exception as e:
            raise Exception(f"Error generating article with Gemini: {str(e)}")
    
    def _build_prompt(self, 
                      product_info: Dict[str, Any],
                      article_type: str,
                      tone: str,
                      keywords: str,
                      length: str,
                      include_comparison: str,
                      target_audience: str,
                      seo_focus: str) -> str:
        """
        Build a comprehensive prompt for Gemini
        """
        
        offer_name = product_info.get('offer', '')
        dest_url = product_info.get('dest_url', '')
        
        # Determine word count based on length
        word_counts = {
            'short': '500-800',
            'medium': '800-1200', 
            'long': '1200-1500'
        }
        word_count = word_counts.get(length, '800-1200')
        
        prompt = f"""You are an expert content writer specializing in eco-friendly pet products and affiliate marketing. 

Write a {article_type} article about {offer_name} with the following specifications:

**Article Requirements:**
- Type: {article_type}
- Tone: {tone}
- Length: {word_count} words
- Target Audience: {target_audience}
- SEO Focus: {seo_focus}
- Keywords to include: {keywords}

**Product Information:**
- Product: {offer_name}
- Affiliate URL: {dest_url}

**Content Guidelines:**
- Focus on eco-friendly and sustainable aspects
- Include practical benefits for pet owners
- Use natural, engaging language
- Incorporate the specified keywords naturally
- Make it informative and helpful
- Include specific product features and benefits
- Write in {tone} tone
- Target {target_audience}

**Structure:**
- Compelling headline
- Introduction that hooks the reader
- Clear sections with subheadings
- Product overview and features
- Benefits and advantages
- Practical usage tips
- Conclusion with recommendation

**Important:**
- Write in Markdown format
- Do NOT include affiliate links or CTAs (I'll add those separately)
- Focus on providing genuine value to readers
- Make it engaging and informative
- Use the exact tone and style specified

Generate the article now:"""

        if include_comparison == "yes":
            prompt += "\n\n**Include a product comparison section** that compares this product to alternatives in the market."
        
        return prompt
    
    def _clean_response(self, response: str) -> str:
        """Clean up Gemini's response"""
        # Remove any system messages or extra formatting
        lines = response.split('\n')
        cleaned_lines = []
        
        for line in lines:
            # Skip lines that look like system messages
            if line.strip().startswith('```') or line.strip().startswith('Assistant:'):
                continue
            if line.strip() == '' and not cleaned_lines:  # Skip leading empty lines
                continue
            cleaned_lines.append(line)
        
        # Join and clean up
        cleaned = '\n'.join(cleaned_lines).strip()
        
        # Remove markdown code blocks if present
        cleaned = re.sub(r'```markdown\s*', '', cleaned)
        cleaned = re.sub(r'```\s*$', '', cleaned)
        
        return cleaned
    
    def _add_affiliate_elements(self, article_content: str, product_info: Dict[str, Any]) -> str:
        """Add affiliate disclosure and call-to-action"""
        
        offer_name = product_info.get('offer', '')
        slug = product_info.get('slug', '')
        
        # Add affiliate disclosure at the top
        disclosure = f"> \n\n"
        
        # Add CTA at the end
        cta = f"""

---

**Try this:** [{offer_name}](http://127.0.0.1:8088/r/{slug}?utm_source=site&utm_medium=cta&utm_campaign=ai-generated)
*We might earn a commission at no cost to you.*
"""
        
        return disclosure + article_content + cta
    
    def test_connection(self) -> bool:
        """Test if Gemini API is accessible"""
        try:
            # Try a simple generation to test the connection
            test_response = self.model.generate_content("Say 'Hello, Gemini API is working!'")
            return bool(test_response.text and "Hello" in test_response.text)
        except Exception:
            return False

# Test function
if __name__ == "__main__":
    try:
        generator = GeminiArticleGenerator()
        if generator.test_connection():
            print("✅ Gemini API connection successful!")
        else:
            print("❌ Cannot connect to Gemini API. Check your API key.")
    except ValueError as e:
        print(f"❌ Configuration error: {e}")
    except Exception as e:
        print(f"❌ Error testing Gemini API: {e}")
